# Site-wide settings

title: Code Journey
author:
  name: cskime
  email: kcsol1005@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  History of my journey in coding and learning
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cskime.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

## Disable deprecation warnings
sass:
  quiet_deps: true
  silence_deprecations: [import]

# Minima-specific settings (v3 or above)

minima:
  skin: auto
  nav_pages:
    - about.md
  social_links:
    - title: "GitHub"
      icon: "github"
      url: "https://github.com/cskime"
    - title: "LinkedIn"
      icon: "linkedin"
      url: "https://www.linkedin.com/in/chamsolkim/"
